- name: apt update
  become: true
  apt:
    update_cache: yes
- name: apt install packages
  become: true
  apt:
    name:
      - wget
      - sudo
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli

- name: copy vim setting file
  copy:
    src: "{{ item }}"
    dest: /home/pi/
    mode: 0755
  with_items:
    - ../files/vim/.vimrc
    - ../files/vim/.gvimrc
